### ISSUE TITLE
GPIO callback

### ISSUE THREAD

**Issue by royben** [apead/Xamarin-Android-Things#1]
Hi there,
Any idea why GPIO callback might not work on raspberry pi 3?

This is how I register:
```
 _btnPin = service.OpenGpio("BCM19");
            _btnPin.SetDirection(Gpio.DirectionIn);
            _btnPin.SetActiveType(Gpio.ActiveHigh);
            _btnPin.SetEdgeTriggerType(Gpio.EdgeRising);
            _btnPin.RegisterGpioCallback(_callback);
```

Same input number works on Windows IOT core.

**Comment by apead** [comment]
I'll have a look later today and do some tests.  It's possible that BCM19 is allocated as a I2S Pin.   https://developer.android.com/things/hardware/raspberrypi-io.html

Also some more info on callbacks in meantime:  http://explorationspace.co.za/2017/02/26/android-things-gpio-callbacks/

**Comment by royben** [comment]
Hi, 
Actually I managed to solve this by re-wiring the button in a different way.

**Comment by royben** [comment]
Thanks!

**Comment by apead** [comment]
Different how?

**Comment by royben** [comment]
It is ok.

**Comment by apead** [comment]
The bindings used here have been upgraded to Android Things Support Library 0.41 Preview.
